services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: jaeger
        ports:
            - "16686:16686" # Jaeger UI
            - "4317:4317" # OTLP gRPC
            - "4318:4318" # OTLP HTTP
        networks:
            - event-booking-network
    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        container_name: otel-collector
        command: ["--config=/etc/otel-collector-config.yml"]
        volumes:
            - ./otel/otel-collector-config.yml:/etc/otel-collector-config.yml
        ports:
            - "4319:4317"
        depends_on:
            - jaeger
        networks:
            - event-booking-network
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        ports:
            - "9090:9090"
        depends_on:
            - notification-service
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - event-booking-network
    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3010:3000"
        depends_on:
            - prometheus
        networks:
            - event-booking-network
    kafka-server:
        image: apache/kafka:4.3.0
        container_name: kafka-server
        ports:
            - "9092:9092"
        environment:
            # KRaft mode
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: broker,controller
            KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-server:9093

            # listeners
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092

            KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

            # single broker dev mode
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        healthcheck:
            test: ["CMD-SHELL", "bash -c 'nc -z localhost 9092'"]
            interval: 10s
            timeout: 5s
            retries: 10
            start_period: 20s
        networks:
            - event-booking-network
        volumes:
            - kafka-data:/var/lib/kafka/data
    event-db:
        image: postgres:14-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: event-service
        ports:
            - 5432:5432
        volumes:
            - event-service-db-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d event-service"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s
        networks:
            - event-booking-network
    notification-db:
        image: mongo:latest
        container_name: notification-db
        ports:
            - "27017:27017"
        environment:
            # Sets the root username and password
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
        networks:
            - event-booking-network
        volumes:
            - notification-db-data:/data/db
        healthcheck:
            test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
    notification-service:
        build:
            context: .
            dockerfile: ./apps/notification-service/Dockerfile
        ports:
            - "3001:3001"
        env_file:
            - ./apps/notification-service/.env.dev
        networks:
            - event-booking-network
        depends_on:
            notification-db:
                condition: service_healthy
            kafka-server:
                condition: service_healthy
            otel-collector:
                condition: service_started
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--spider",
                    "-q",
                    "http://localhost:3001/health",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        restart: always
    event-service-migrations:
        build:
            context: .
            dockerfile: ./apps/event-service/Dockerfile
        env_file:
            - ./apps/event-service/.env.dev
        depends_on:
            event-db:
                condition: service_healthy
        command: npx drizzle-kit migrate
        networks:
            - event-booking-network
    event-service:
        build:
            context: .
            dockerfile: ./apps/event-service/Dockerfile
        env_file:
            - ./apps/event-service/.env.dev
        ports:
            - "3002:3002"
        networks:
            - event-booking-network
        depends_on:
            event-db:
                condition: service_healthy
            event-service-migrations:
                condition: service_completed_successfully
            kafka-server:
                condition: service_healthy
            otel-collector:
                condition: service_started
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--spider",
                    "-q",
                    "http://localhost:3002/health",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 20s
        restart: always
volumes:
    notification-db-data:
    event-service-db-data:
    kafka-data:
networks:
    event-booking-network:
        driver: bridge
