name: CI-notification-service-Lint
on:
    push:
        branches:
            - main
            - dev
            - feat/**
            - fix/**
        paths:
            - "apps/notification-service/**"
            - ".github/workflows/notification-service-lint.yaml"
    pull_request:
        branches:
            - main
            - dev
permissions:
    contents: read
concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref != 'refs/heads/main' }}
jobs:
    notification-service-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Initialize Environment
              uses: ./.github/actions/setup-node-and-cache
              with:
                  node-version: 20
                  pnpm-version: 10.26.1
            - name: Run lint
              run: pnpm --filter ./apps/notification-service run lint
