name: CI-service-Test
on:
    workflow_call:
        inputs:
            node-version:
                description: Node.js version
                required: true
                type: string
            pnpm-version:
                description: Pnpm version
                required: true
                type: string
            service-name:
                description: Service name
                required: true
                type: string
jobs:
    service-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Initialize Environment
              uses: ./.github/actions/setup-node-and-cache
              with:
                  node-version: ${{ inputs.node-version }}
                  pnpm-version: ${{ inputs.pnpm-version }}
            # Build internal dependencies
            - name: Build Shared Logger
              run: pnpm --filter @event-booking/logger run build
            - name: Build Shared Message Broker
              run: pnpm --filter @event-booking/message-broker run build
            - name: Run tests
              run: pnpm run --filter ./apps/${{ inputs.service-name }} test
